/* tslint:disable */
/* eslint-disable */
/**
 * PMS.Api
 * Pharmacy Management System API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface AssignEmployeeIM
 */
export interface AssignEmployeeIM {
    /**
     * 
     * @type {string}
     * @memberof AssignEmployeeIM
     */
    email?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AssignEmployeeIM
     */
    password?: string | null;
}
