/* tslint:disable */
/* eslint-disable */
/**
 * PMS.Api
 * Pharmacy Management System API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface BasicMedicineVM
 */
export interface BasicMedicineVM {
    /**
     * 
     * @type {string}
     * @memberof BasicMedicineVM
     */
    id?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BasicMedicineVM
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BasicMedicineVM
     */
    description?: string | null;
}
