/* tslint:disable */
/* eslint-disable */
/**
 * PMS.Api
 * Pharmacy Management System API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ChangePasswordIM
 */
export interface ChangePasswordIM {
    /**
     * 
     * @type {string}
     * @memberof ChangePasswordIM
     */
    oldPassword: string;
    /**
     * 
     * @type {string}
     * @memberof ChangePasswordIM
     */
    newPassword: string;
}
