/* tslint:disable */
/* eslint-disable */
/**
 * PMS.Api
 * Pharmacy Management System API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Address } from './address';
/**
 * 
 * @export
 * @interface DepotIM
 */
export interface DepotIM {
    /**
     * 
     * @type {string}
     * @memberof DepotIM
     */
    name: string;
    /**
     * 
     * @type {Address}
     * @memberof DepotIM
     */
    address: Address;
}
