/* tslint:disable */
/* eslint-disable */
/**
 * PMS.Api
 * Pharmacy Management System API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface MedicineInvoiceModel
 */
export interface MedicineInvoiceModel {
    /**
     * 
     * @type {string}
     * @memberof MedicineInvoiceModel
     */
    id?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MedicineInvoiceModel
     */
    name?: string | null;
    /**
     * 
     * @type {number}
     * @memberof MedicineInvoiceModel
     */
    price?: number;
    /**
     * 
     * @type {number}
     * @memberof MedicineInvoiceModel
     */
    quantity?: number;
}
