/* tslint:disable */
/* eslint-disable */
/**
 * PMS.Api
 * Pharmacy Management System API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BasicMedicineVM } from './basic-medicine-vm';
import { DateOnly } from './date-only';
/**
 * 
 * @export
 * @interface MedicineVM
 */
export interface MedicineVM {
    /**
     * 
     * @type {string}
     * @memberof MedicineVM
     */
    id?: string | null;
    /**
     * 
     * @type {number}
     * @memberof MedicineVM
     */
    price?: number;
    /**
     * 
     * @type {DateOnly}
     * @memberof MedicineVM
     */
    expirationDate?: DateOnly;
    /**
     * 
     * @type {string}
     * @memberof MedicineVM
     */
    imageUrl?: string | null;
    /**
     * 
     * @type {number}
     * @memberof MedicineVM
     */
    quantity?: number;
    /**
     * 
     * @type {boolean}
     * @memberof MedicineVM
     */
    isExpired?: boolean;
    /**
     * 
     * @type {BasicMedicineVM}
     * @memberof MedicineVM
     */
    basicMedicine?: BasicMedicineVM;
    /**
     * 
     * @type {string}
     * @memberof MedicineVM
     */
    createdBy?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof MedicineVM
     */
    createdOn?: Date;
    /**
     * 
     * @type {string}
     * @memberof MedicineVM
     */
    updatedBy?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof MedicineVM
     */
    updatedOn?: Date;
}
