/* tslint:disable */
/* eslint-disable */
/**
 * PMS.Api
 * Pharmacy Management System API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface MedicineIM
 */
export interface MedicineIM {
    /**
     * 
     * @type {string}
     * @memberof MedicineIM
     */
    basicMedicineId: string;
    /**
     * 
     * @type {number}
     * @memberof MedicineIM
     */
    price: number;
    /**
     * 
     * @type {number}
     * @memberof MedicineIM
     */
    quantity: number;
    /**
     * 
     * @type {string}
     * @memberof MedicineIM
     */
    expirationDate?: string | null;
}
