/* tslint:disable */
/* eslint-disable */
/**
 * PMS.Api
 * Pharmacy Management System API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DateOnly } from './date-only';
/**
 * 
 * @export
 * @interface NotificationVM
 */
export interface NotificationVM {
    /**
     * 
     * @type {string}
     * @memberof NotificationVM
     */
    id?: string | null;
    /**
     * 
     * @type {string}
     * @memberof NotificationVM
     */
    text?: string | null;
    /**
     * 
     * @type {DateOnly}
     * @memberof NotificationVM
     */
    sentOn?: DateOnly;
    /**
     * 
     * @type {boolean}
     * @memberof NotificationVM
     */
    isAssignRequest?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof NotificationVM
     */
    isWarning?: boolean;
    /**
     * 
     * @type {string}
     * @memberof NotificationVM
     */
    pharmacyId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof NotificationVM
     */
    depotId?: string | null;
}
