/* tslint:disable */
/* eslint-disable */
/**
 * PMS.Api
 * Pharmacy Management System API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Address } from './address';
import { DepotVM } from './depot-vm';
import { MedicineVM } from './medicine-vm';
import { UserVM } from './user-vm';
/**
 * 
 * @export
 * @interface PharmacyVM
 */
export interface PharmacyVM {
    /**
     * 
     * @type {string}
     * @memberof PharmacyVM
     */
    id?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PharmacyVM
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PharmacyVM
     */
    description?: string | null;
    /**
     * 
     * @type {Address}
     * @memberof PharmacyVM
     */
    address?: Address;
    /**
     * 
     * @type {UserVM}
     * @memberof PharmacyVM
     */
    founder?: UserVM;
    /**
     * 
     * @type {DepotVM}
     * @memberof PharmacyVM
     */
    depot?: DepotVM;
    /**
     * 
     * @type {Array<UserVM>}
     * @memberof PharmacyVM
     */
    pharmacists?: Array<UserVM> | null;
    /**
     * 
     * @type {Array<MedicineVM>}
     * @memberof PharmacyVM
     */
    medicines?: Array<MedicineVM> | null;
    /**
     * 
     * @type {string}
     * @memberof PharmacyVM
     */
    createdBy?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof PharmacyVM
     */
    createdOn?: Date;
    /**
     * 
     * @type {string}
     * @memberof PharmacyVM
     */
    updatedBy?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof PharmacyVM
     */
    updatedOn?: Date;
}
