/* tslint:disable */
/* eslint-disable */
/**
 * PMS.Api
 * Pharmacy Management System API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface RefillIM
 */
export interface RefillIM {
    /**
     * 
     * @type {string}
     * @memberof RefillIM
     */
    pharmacyId?: string | null;
    /**
     * 
     * @type {number}
     * @memberof RefillIM
     */
    quantity?: number;
}
