/* tslint:disable */
/* eslint-disable */
/**
 * PMS.Api
 * Pharmacy Management System API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface RegisterIM
 */
export interface RegisterIM {
    /**
     * 
     * @type {string}
     * @memberof RegisterIM
     */
    firstName: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterIM
     */
    lastName: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterIM
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterIM
     */
    phoneNumber: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterIM
     */
    password: string;
}
