/* tslint:disable */
/* eslint-disable */
/**
 * PMS.Api
 * Pharmacy Management System API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface UserUM
 */
export interface UserUM {
    /**
     * 
     * @type {string}
     * @memberof UserUM
     */
    email?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserUM
     */
    firstName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserUM
     */
    lastName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserUM
     */
    phoneNumber?: string | null;
}
